
########################################  Running CUTe test(s)  ########################################

check_uint_suite::check_uint_literal_equal_fail_test .............................................. fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:17
caller: check_uint_literal_equal_fail_test__cute_exec()
wanted: 0 == 1
found:  [0] != [1]

check_uint_suite::check_uint_var_equal_fail_test .................................................. fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:24
caller: check_uint_var_equal_fail_test__cute_exec()
wanted: chk == 1
found:  [2] != [1]

check_uint_suite::check_uint_equal_ref_fail_test .................................................. fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:31
caller: check_uint_equal_ref_fail_test__cute_exec()
wanted: 1 == ref
found:  [1] != [2]

check_uint_suite::check_uint_var_equal_ref_fail_test .............................................. fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:39
caller: check_uint_var_equal_ref_fail_test__cute_exec()
wanted: chk == ref
found:  [2] != [3]

check_uint_suite::check_uint_literal_unequal_fail_test ............................................ fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:56
caller: check_uint_literal_unequal_fail_test__cute_exec()
wanted: 1 != 1
found:  [1] == [1]

check_uint_suite::check_uint_var_unequal_fail_test ................................................ fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:63
caller: check_uint_var_unequal_fail_test__cute_exec()
wanted: chk != 2
found:  [2] == [2]

check_uint_suite::check_uint_unequal_ref_fail_test ................................................ fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:70
caller: check_uint_unequal_ref_fail_test__cute_exec()
wanted: 2 != ref
found:  [2] == [2]

check_uint_suite::check_uint_var_unequal_ref_fail_test ............................................ fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:78
caller: check_uint_var_unequal_ref_fail_test__cute_exec()
wanted: chk != ref
found:  [2] == [2]

check_uint_suite::check_uint_literal_greater_fail_test ............................................ fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:94
caller: check_uint_literal_greater_fail_test__cute_exec()
wanted: 1 > 1
found:  [1] <= [1]

check_uint_suite::check_uint_var_greater_fail_test ................................................ fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:101
caller: check_uint_var_greater_fail_test__cute_exec()
wanted: chk > 1
found:  [0] <= [1]

check_uint_suite::check_uint_greater_ref_fail_test ................................................ fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:108
caller: check_uint_greater_ref_fail_test__cute_exec()
wanted: 0 > ref
found:  [0] <= [1]

check_uint_suite::check_uint_var_greater_ref_fail_test ............................................ fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:116
caller: check_uint_var_greater_ref_fail_test__cute_exec()
wanted: chk > ref
found:  [1] <= [10]

check_uint_suite::check_uint_literal_greater_equal_fail_test ...................................... fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:135
caller: check_uint_literal_greater_equal_fail_test__cute_exec()
wanted: 0 >= 1
found:  [0] < [1]

check_uint_suite::check_uint_var_greater_equal_fail_test .......................................... fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:142
caller: check_uint_var_greater_equal_fail_test__cute_exec()
wanted: chk >= 1
found:  [0] < [1]

check_uint_suite::check_uint_greater_equal_ref_fail_test .......................................... fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:149
caller: check_uint_greater_equal_ref_fail_test__cute_exec()
wanted: 0 >= ref
found:  [0] < [1]

check_uint_suite::check_uint_var_greater_equal_ref_fail_test ...................................... fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:157
caller: check_uint_var_greater_equal_ref_fail_test__cute_exec()
wanted: chk >= ref
found:  [0] < [10]

check_uint_suite::check_uint_literal_lower_fail_test .............................................. fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:173
caller: check_uint_literal_lower_fail_test__cute_exec()
wanted: 0 < 0
found:  [0] >= [0]

check_uint_suite::check_uint_var_lower_fail_test .................................................. fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:180
caller: check_uint_var_lower_fail_test__cute_exec()
wanted: chk < 0
found:  [1] >= [0]

check_uint_suite::check_uint_lower_ref_fail_test .................................................. fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:187
caller: check_uint_lower_ref_fail_test__cute_exec()
wanted: 10 < ref
found:  [10] >= [10]

check_uint_suite::check_uint_var_lower_ref_fail_test .............................................. fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:195
caller: check_uint_var_lower_ref_fail_test__cute_exec()
wanted: chk < ref
found:  [1] >= [0]

check_uint_suite::check_uint_literal_lower_equal_fail_test ........................................ fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:214
caller: check_uint_literal_lower_equal_fail_test__cute_exec()
wanted: 1 <= 0
found:  [1] > [0]

check_uint_suite::check_uint_var_lower_equal_fail_test ............................................ fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:221
caller: check_uint_var_lower_equal_fail_test__cute_exec()
wanted: chk <= 0
found:  [1] > [0]

check_uint_suite::check_uint_lower_equal_ref_fail_test ............................................ fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:228
caller: check_uint_lower_equal_ref_fail_test__cute_exec()
wanted: 10 <= ref
found:  [10] > [1]

check_uint_suite::check_uint_var_lower_equal_ref_fail_test ........................................ fail
issue:  exec failed
reason: unsigned integer value check failed
source: cute/test/check_uint.c:236
caller: check_uint_var_lower_equal_ref_fail_test__cute_exec()
wanted: chk <= ref
found:  [10] > [0]

check_uint_suite::check_uint_literal_in_range_fail_test ........................................... fail
issue:  exec failed
reason: unsigned integer range check failed
source: cute/test/check_uint.c:256
caller: check_uint_literal_in_range_fail_test__cute_exec()
wanted: 0 in range {1 ... 10}
found:  [0] not in range {1 ... 10}

check_uint_suite::check_uint_var_in_range_fail_test ............................................... fail
issue:  exec failed
reason: unsigned integer range check failed
source: cute/test/check_uint.c:263
caller: check_uint_var_in_range_fail_test__cute_exec()
wanted: chk in range {1 ... 10}
found:  [11] not in range {1 ... 10}

check_uint_suite::check_uint_in_range_ref_fail_test ............................................... fail
issue:  exec failed
reason: unsigned integer range check failed
source: cute/test/check_uint.c:272
caller: check_uint_in_range_ref_fail_test__cute_exec()
wanted: 0 in range {min_ref ... max_ref}
found:  [0] not in range {5 ... 5}

check_uint_suite::check_uint_var_in_range_ref_fail_test ........................................... fail
issue:  exec failed
reason: unsigned integer range check failed
source: cute/test/check_uint.c:283
caller: check_uint_var_in_range_ref_fail_test__cute_exec()
wanted: chk in range {min_ref ... max_ref}
found:  [6] not in range {5 ... 5}

check_uint_suite::check_uint_literal_not_in_range_fail_test ....................................... fail
issue:  exec failed
reason: unsigned integer range check failed
source: cute/test/check_uint.c:303
caller: check_uint_literal_not_in_range_fail_test__cute_exec()
wanted: 1 not in range {1 ... 10}
found:  [1] in range {1 ... 10}

check_uint_suite::check_uint_var_not_in_range_fail_test ........................................... fail
issue:  exec failed
reason: unsigned integer range check failed
source: cute/test/check_uint.c:310
caller: check_uint_var_not_in_range_fail_test__cute_exec()
wanted: chk not in range {1 ... 10}
found:  [10] in range {1 ... 10}

check_uint_suite::check_uint_not_in_range_ref_fail_test ........................................... fail
issue:  exec failed
reason: unsigned integer range check failed
source: cute/test/check_uint.c:319
caller: check_uint_not_in_range_ref_fail_test__cute_exec()
wanted: 5 not in range {min_ref ... max_ref}
found:  [5] in range {1 ... 10}

check_uint_suite::check_uint_var_not_in_range_ref_fail_test ....................................... fail
issue:  exec failed
reason: unsigned integer range check failed
source: cute/test/check_uint.c:330
caller: check_uint_var_not_in_range_ref_fail_test__cute_exec()
wanted: chk not in range {min_ref ... max_ref}
found:  [5] in range {5 ... 5}

check_uint_suite::check_uint_literal_in_set_fail_test ............................................. fail
issue:  exec failed
reason: unsigned integer set check failed
source: cute/test/check_uint.c:350
caller: check_uint_literal_in_set_fail_test__cute_exec()
wanted: 10 in set {0, 1, 2, 3, 5, 8}
found:  [10] not in set {0, 1, 2, 3, 5, 8}

check_uint_suite::check_uint_var_in_set_fail_test ................................................. fail
issue:  exec failed
reason: unsigned integer set check failed
source: cute/test/check_uint.c:357
caller: check_uint_var_in_set_fail_test__cute_exec()
wanted: chk in set {0, 1, 2, 3, 5, 8}
found:  [4] not in set {0, 1, 2, 3, 5, 8}

check_uint_suite::check_uint_in_set_ref_fail_test ................................................. fail
issue:  exec failed
reason: unsigned integer set check failed
source: cute/test/check_uint.c:367
caller: check_uint_in_set_ref_fail_test__cute_exec()
wanted: 4 in set {ref0, 1, 2, 3, ref5, 8}
found:  [4] not in set {0, 1, 2, 3, 5, 8}

check_uint_suite::check_uint_var_in_set_ref_fail_test ............................................. fail
issue:  exec failed
reason: unsigned integer set check failed
source: cute/test/check_uint.c:379
caller: check_uint_var_in_set_ref_fail_test__cute_exec()
wanted: chk in set {ref0, 1, 2, 3, ref5, 8}
found:  [10] not in set {0, 1, 2, 3, 5, 8}

check_uint_suite::check_uint_literal_not_in_set_fail_test ......................................... fail
issue:  exec failed
reason: unsigned integer set check failed
source: cute/test/check_uint.c:399
caller: check_uint_literal_not_in_set_fail_test__cute_exec()
wanted: 1 not in set {0, 1, 2, 3, 5, 8}
found:  [1] in set {0, 1, 2, 3, 5, 8}

check_uint_suite::check_uint_var_not_in_set_fail_test ............................................. fail
issue:  exec failed
reason: unsigned integer set check failed
source: cute/test/check_uint.c:406
caller: check_uint_var_not_in_set_fail_test__cute_exec()
wanted: chk not in set {0, 1, 2, 3, 5, 8}
found:  [8] in set {0, 1, 2, 3, 5, 8}

check_uint_suite::check_uint_not_in_set_ref_fail_test ............................................. fail
issue:  exec failed
reason: unsigned integer set check failed
source: cute/test/check_uint.c:416
caller: check_uint_not_in_set_ref_fail_test__cute_exec()
wanted: 0 not in set {ref0, 1, 2, 3, ref5, 8}
found:  [0] in set {0, 1, 2, 3, 5, 8}

check_uint_suite::check_uint_var_not_in_set_ref_fail_test ......................................... fail
issue:  exec failed
reason: unsigned integer set check failed
source: cute/test/check_uint.c:428
caller: check_uint_var_not_in_set_ref_fail_test__cute_exec()
wanted: chk not in set {ref0, 1, 2, 3, ref5, 8}
found:  [5] in set {0, 1, 2, 3, 5, 8}

check_uint_suite .................................................................................. fail
issue:  exec failed
reason: descendants failed
source: cute/test/check_uint.c:493

NAME                                          STAT  TIME(s.us)  #PASS  #SKIP  #FAIL  #EXCP  #EXEC #TOTAL
check_uint_suite                              fail    0.162294     10      0     40      0     50     50
                                                                  20%     0%    80%     0%   100%
--------------------------------------------------------------------------------------------------------
Total                                         fail    0.162294     10      0     40      0     50     50
                                                                  20%     0%    80%     0%   100%

                                  ###           SUMMARY            ###
                                  ###  40/50 (80%) test(s) FAILED  ###

